name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Substitua por 'master' se esse for o branch principal do repositório.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Certifique-se de que esta é a versão correta para o seu projeto

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4. Gerar o build
      - name: Build project
        run: npm run build

      # 5. Deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
